#!/bin/sh
# 
# /etc/rc.d/iptables - personal firewall script
#

case $1 in
start)
	/usr/sbin/iptables -F
	/usr/sbin/iptables -P INPUT DROP
	/usr/sbin/iptables -P OUTPUT ACCEPT
	/usr/sbin/iptables -P FORWARD DROP
	/usr/sbin/iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
	/usr/sbin/iptables -A INPUT -i lo -j ACCEPT
	/usr/sbin/iptables -A OUTPUT -o lo -j ACCEPT
        ;;
stop)
	/usr/sbin/iptables -F
	/usr/sbin/iptables -P INPUT ACCEPT
	/usr/sbin/iptables -P OUTPUT ACCEPT
	/usr/sbin/iptables -P FORWARD ACCEPT
        ;;
restart)
        $0 stop
        $0 start
        ;;
*)
        echo "usage: $0 [start|stop|restart]"
        ;;
esac

# End of file
